# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

name: Build Identity Provider

on:
  push:
    paths: 
      - 'src/admin/**'
  workflow_dispatch:

jobs:
  Build:
    name: Restore Build and Test
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build Identity Provider
        run: dotnet build ./src/admin/AMP.Identity/AMP.Identity.csproj --configuration Release

      - name: Test
        run: dotnet test ./tests/admin/AMP.Identity.Test --verbosity normal --logger trx --collect:"XPlat Code Coverage"

      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 5
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"