# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

name: Deploy Development

on:
  workflow_dispatch:

jobs:
  Deploy-EMS-API:
    name: Deploy EMS API
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ems-api
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1828134816E746A089EC5C15FB317D16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_190BF6DB857748C38162835A22FB2FFB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D97FDA82D944EB8AA433AB2685C0AD1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amp-ems-api-dev'
          slot-name: 'Production'
          package: .

  Deploy-IdP-API:
    name: Deploy IdP API
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: idp-api
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E72561306CA400EBC72036080D49248 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_62C62560DE684B49949263B7116C07BF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D63F152DF0648F7BDA032E480653201 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amp-idp-api-dev'
          slot-name: 'Production'
          package: .