# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

name: Development

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  Build:
    name: Restore Build and Test
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build Identity
        run: dotnet build ./src/admin/AMP.Identity/AMP.Identity.csproj --configuration Release

      - name: Build EMS API
        run: dotnet build ./src/api/AMP.EMS.API/AMP.EMS.API.csproj --configuration Release

      - name: Test
        run: dotnet test --verbosity normal --logger trx --collect:"XPlat Code Coverage"

      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 5
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"

  Publish-Identity:
      name: Publish Identity
      needs: Build
      runs-on: ubuntu-latest   
      steps:
        - uses: actions/checkout@v4
        - name: Set up .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.x'
        - name: Restore dependencies
          run: dotnet restore
        - name: Publish Identity
          run: dotnet publish ./src/admin/AMP.Identity/AMP.Identity.csproj -c Release -o ${{env.DOTNET_ROOT}}/idp
        - name: Upload Identity
          uses: actions/upload-artifact@v4
          with:
            name: idp
            path: ${{env.DOTNET_ROOT}}/idp

  Publish-EMS-API:
    name: Publish EMS API
    needs: Build
    runs-on: ubuntu-latest        

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish EMS API
        run: dotnet publish ./src/api/AMP.EMS.API/AMP.EMS.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/ems-api

      - name: Upload EMS API
        uses: actions/upload-artifact@v4
        with:
          name: ems-api
          path: ${{env.DOTNET_ROOT}}/ems-api

  Deploy-Identity:
      name: Deploy Identity
      runs-on: ubuntu-latest
      needs: Publish-Identity
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      permissions:
        id-token: write #This is required for requesting the JWT
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: idp
        
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DE723C34555542DA86E36ED0282BFDAC }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39F4F690335F4CD8BCAB6AEDD38B8DBE }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_846825B2A1DC4C8189C2F65766A8DC90 }}
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: 'amp-idp'
            slot-name: 'Production'
            package: .

  Deploy-EMS-API:
    name: Deploy EMS API
    runs-on: ubuntu-latest
    needs: Publish-EMS-API
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ems-api
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1828134816E746A089EC5C15FB317D16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_190BF6DB857748C38162835A22FB2FFB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D97FDA82D944EB8AA433AB2685C0AD1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amp-ems-api-dev'
          slot-name: 'Production'
          package: .