# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

name: Development Build API

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  Publish-EMS-API:
    name: Publish EMS API
    runs-on: ubuntu-latest        

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish EMS API
        run: dotnet publish ./src/api/AMP.EMS.API/AMP.EMS.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/ems-api

      - name: Upload EMS API
        uses: actions/upload-artifact@v4
        with:
          name: ems-api
          path: ${{env.DOTNET_ROOT}}/ems-api

  Deploy-EMS-API:
    name: Deploy EMS API
    runs-on: ubuntu-latest
    needs: Publish-EMS-API
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ems-api
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1828134816E746A089EC5C15FB317D16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_190BF6DB857748C38162835A22FB2FFB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D97FDA82D944EB8AA433AB2685C0AD1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amp-ems-api-dev'
          slot-name: 'Production'
          package: .