# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: UI Workflow

on:
  push:
    paths: 
      - 'src/ui/AMP.EMS/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: 'Development'
    defaults:
      run:
         working-directory: ./src/ui/AMP.EMS

    strategy:
       matrix:
         node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm install
      working-directory: ./src/ui/AMP.EMS
    - run: npm run build
      working-directory: ./src/ui/AMP.EMS
   # - run: npm test
   #   working-directory: ./src/ui/AMP.EMS
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: ./src/ui/AMP.EMS/dist

  Deploy-EMS:
    name: Deploy EMS
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EMS_AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.EMS_AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.EMS_AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'amp-ems-dev'
          slot-name: 'Production'
          package: .
