# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

name: API Database

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Database Action'
        required: true
        default: 'Deploy'
        type: choice
        options:
          - 'Migrate'
          - 'Seed'
          - 'Migrate and Seed'

jobs:
  set-environment:
    name: Set Environment
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.output-environment-name.outputs.environment_name }}
    steps:
      - id: output-environment-name
        run: echo "environment_name=${{ github.ref == 'refs/heads/master' && 'Production' || 'Development' }}" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy to ${{ needs.set-environment.outputs.environment_name }}
    needs: set-environment
    if: ${{ (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'Deploy' )) && needs.set-environment.outputs.environment_name != '' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-environment.outputs.environment_name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    
    steps:   
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ems-api

      - name: Substitute appsettings
        uses: microsoft/variable-substitution@v1 
        with:
          files: './appsettings*.json'
        env:
          ConnectionStrings.DefaultConnection: ${{secrets.EMS_API_DB_CONNECTION_STRING}}
          Authority: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/
          Serilog.WriteTo.0.Args.serverUrl: ${{vars.SEQ_URL}}
          DatabaseConfiguration.Type: ${{vars.EMS_API_DB_TYPE}}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '${{vars.EMS_AZUREAPPSERVICE_APPNAME}}'
          slot-name: 'Production'
          package: .
          target-path: '/home/site/wwwroot/api'

  update-database:
    name: ${{ github.event.inputs.action }} ${{ needs.set-environment.outputs.environment_name }} Database
    needs: set-environment
    if: ${{ github.event_name == 'workflow_dispatch' && needs.set-environment.outputs.environment_name != '' }}
    environment:
      name: ${{ needs.set-environment.outputs.environment_name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Substitute appsettings
        uses: microsoft/variable-substitution@v1 
        with:
          files: './src/api/AMP.EMS.API/appsettings*.json'
        env:
          ConnectionStrings.DefaultConnection: ${{secrets.EMS_API_DB_CONNECTION_STRING}}
          DatabaseConfiguration.Type: ${{vars.EMS_API_DB_TYPE}}

      - name: Migrate
        if: ${{ github.event.inputs.action == 'Migrate' }}
        run: dotnet run ./src/api/AMP.EMS.API/AMP.EMS.API.csproj /migrate

      - name: Seed
        if: ${{ github.event.inputs.action == 'Seed' }}
        run: dotnet run ./src/api/AMP.EMS.API/AMP.EMS.API.csproj /seed

      - name: Migrate and Seed
        if: ${{ github.event.inputs.action == 'Migrate and Seed' }}
        run: dotnet run ./src/api/AMP.EMS.API/AMP.EMS.API.csproj /migrate /seed