# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

name: Production API 

on:
  push:
    paths: 
      - 'src/api/**'
      - 'src/common/**'
    branches:
      - 'master'
      - 'development'
  workflow_dispatch:

jobs:
  set-environment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment for Deployment
        id: set-environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "Deploying to Production"
            echo "environment=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            echo "Deploying to Development"
            echo "environment=development" >> $GITHUB_ENV
          else
            echo "Unknown branch. Skipping deployment."
            exit 1
          fi
    
  build-test-package:
    name: Build, Test and Package
    runs-on: ubuntu-latest
    needs: set-environment
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build ./src/api/AMP.EMS.API/AMP.EMS.API.csproj --configuration Release

      - name: Test
        run: dotnet test ./tests/api/AMP.EMS.API.Tests --verbosity normal --logger trx --collect:"XPlat Code Coverage"

      - name: Upload Test Result
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 5
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"

      - name: Publish EMS API
        run: dotnet publish ./src/api/AMP.EMS.API/AMP.EMS.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/ems-api

      - name: Upload EMS API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ems-api
          path: ${{env.DOTNET_ROOT}}/ems-a

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    needs: build-test-package
    permissions:
      id-token: write #This is required for requesting the JWT
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ems-api

      - name: Substitute appsettings
        uses: microsoft/variable-substitution@v1 
        with:
          files: './appsettings*.json'
        env:
          ConnectionStrings.DefaultConnection: ${{secrets.EMS_API_DB_CONNECTION_STRING}}
          Authority: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/
          Serilog.WriteTo.0.Args.serverUrl: ${{vars.SEQ_URL}}
          DatabaseConfiguration.Type: ${{vars.EMS_API_DB_TYPE}}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '${{vars.EMS_AZUREAPPSERVICE_APPNAME}}'
          slot-name: 'Production'
          package: .
          target-path: '/home/site/wwwroot/api'
