# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/

name: Identity Provider

on:
  push:
    paths: 
      - 'src/admin/**'
  workflow_dispatch:

jobs:
  build-test-package:
    name: Build, Test and Package
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build Identity Provider
        run: dotnet build ./src/admin/AMP.Identity/AMP.Identity.csproj --configuration Release

      - name: Test
        run: dotnet test ./tests/admin/AMP.Identity.Test --verbosity normal --logger trx --collect:"XPlat Code Coverage"

      - name: Upload Test Result Files
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/**/TestResults/**/*
          retention-days: 5
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          trx_files: "${{ github.workspace }}/**/*.trx"

      - name: Publish Identity Provider
        run: dotnet publish ./src/admin/AMP.Identity/AMP.Identity.csproj -c Release -o ${{env.DOTNET_ROOT}}/idp
        
      - name: Package Identity Provider
        uses: actions/upload-artifact@v4
        with:
          name: idp
          path: ${{env.DOTNET_ROOT}}/idp

  set-environment:
    name: Set Environment
    needs: build-test-package
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.output-environment-name.outputs.environment_name }}
    steps:
      - id: output-environment-name
        run: echo "environment_name=${{ github.ref == 'refs/heads/master' && 'Production' || 'Development' }}" >> "$GITHUB_OUTPUT"

  deploy:
      name: Deploy to ${{ needs.set-environment.outputs.environment_name }}
      runs-on: ubuntu-latest
      needs: set-environment
      environment:
        name: ${{ needs.set-environment.outputs.environment_name }}
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      permissions:
        id-token: write #This is required for requesting the JWT
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: idp

        - name: Substitute appsettings in AMP.Identity
          uses: microsoft/variable-substitution@v1 
          with:
            files: './appsettings*.json'
          env:
            ConnectionStrings.DefaultConnection: ${{secrets.IDP_DB_CONNECTION_STRING}}
            IdentityServer.Key.StorageKind: ${{vars.IDP_STORAGE_KIND}}
            DataProtectionOptions.StorageKind: ${{vars.IDP_STORAGE_KIND}}
            DbType: ${{vars.IDP_DB_TYPE}}
            CorsAllowedOrigin.0: ${{vars.IDP_AUTHORITY_HTTP_URL}}
            CorsAllowedOrigin.1: ${{vars.IDP_AUTHORITY_HTTPS_URL}}
            CorsAllowedOrigin.2: ${{vars.EMS_API_HTTP_URL}}
            CorsAllowedOrigin.3: ${{vars.EMS_API_HTTPS_URL}}
            ApiAuthentication.Authority: ${{vars.IDP_AUTHORITY_HTTPS_URL}}
            ApiAuthentication.ApiName: ${{secrets.IDP_API_NAME}}
            ApiAuthentication.ApiSecret: ${{secrets.IDP_API_SECRET}}
            PrivateServerAuthentication.Authority: ${{vars.IDP_AUTHORITY_HTTPS_URL}}
            PrivateServerAuthentication.ApiUrl: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/api
            PrivateServerAuthentication.ClientId: ${{secrets.IDP_PUBLIC_SERVER_CLIENT_ID}}
            PrivateServerAuthentication.ClientSecret: ${{secrets.IDP_PUBLIC_SERVER_CLIENT_SECRET}}
            PrivateServerAuthentication.Scope: ${{secrets.IDP_PUBLIC_SERVER_CLIENT_SCOPE}}
            EmailApiAuthentication.Authority: ${{vars.IDP_AUTHORITY_HTTPS_URL}}
            EmailApiAuthentication.ApiUrl: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/api
            EmailApiAuthentication.ClientId: ${{secrets.IDP_PUBLIC_SERVER_CLIENT_ID}}
            EmailApiAuthentication.ClientSecret: ${{secrets.IDP_PUBLIC_SERVER_CLIENT_SECRET}}
            EmailApiAuthentication.Scope: ${{secrets.IDP_PUBLIC_SERVER_CLIENT_SCOPE}}
            Serilog.WriteTo.0.Args.serverUrl: ${{vars.SEQ_URL}}

        - name: Substitute appsettings in AMP.Identity.BlazorApp
          uses: microsoft/variable-substitution@v1 
          with:
            files: './wwwroot/appsettings*.json'
          env:
            apiBaseUrl: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/api
            providerOptions.authority: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/
            providerOptions.clientId: ${{secrets.IDP_ADMIN_CLIENT_ID}}
            providerOptions.defaultScopes.2: ${{secrets.IDP_PUBLIC_SERVER_CLIENT_SCOPE}}
            providerOptions.postLogoutRedirectUri: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/authentication/logout-callbackß
            providerOptions.redirectUri: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/authentication/login-callback
            welcomeContenUrl: ${{vars.IDP_AUTHORITY_HTTPS_URL}}/api/welcomefragment
        
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.IDP_AZUREAPPSERVICE_CLIENTID }}
            tenant-id: ${{ secrets.IDP_AZUREAPPSERVICE_TENANTID }}
            subscription-id: ${{ secrets.IDP_AZUREAPPSERVICE_SUBSCRIPTIONID }}
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: '${{vars.EMS_AZUREAPPSERVICE_APPNAME}}'
            slot-name: 'Production'
            package: .
            target-path: '/home/site/wwwroot/idp'
