# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# https://seankilleen.com/2024/03/beautiful-net-test-reports-using-github-actions/


name: Database - API

on:
  workflow_dispatch:
    inputs:
      azure-login:
        description: 'Login to Azure'
        required: false
        type: boolean
      action:
        description: 'Database Action'
        required: true
        default: 'Deploy'
        type: choice
        options:
          - 'Migrate'
          - 'Seed'
          - 'Migrate and Seed'

jobs:
  set-environment:
    name: Set Environment
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.output-environment-name.outputs.environment_name }}
    steps:
      - id: output-environment-name
        run: echo "environment_name=${{ github.ref == 'refs/heads/master' && 'Production' || 'Development' }}" >> "$GITHUB_OUTPUT"

  update-database:
    name: ${{ github.event.inputs.action }} ${{ needs.set-environment.outputs.environment_name }} Database
    needs: set-environment
    if: ${{ github.event_name == 'workflow_dispatch' && needs.set-environment.outputs.environment_name != '' }}
    environment:
      name: ${{ needs.set-environment.outputs.environment_name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef 

      - name: Substitute appsettings
        uses: microsoft/variable-substitution@v1 
        with:
          files: './src/api/AMP.EMS.API/appsettings*.json'
        env:
          ConnectionStrings.DefaultConnection: ${{secrets.EMS_API_DB_CONNECTION_STRING}}
          DatabaseConfiguration.Type: ${{vars.EMS_API_DB_TYPE}}

      - name: Login to Azure
        if: ${{ github.event.inputs.azure-login == 'true' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.EMS_API_AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Run EF Core Migrations
        if: ${{ github.event.inputs.action == 'Migrate' || github.event.inputs.action == 'Migrate and Seed' }}
        working-directory: src/api/AMP.EMS.API
        run: dotnet ef database update --context EmsDbContext --provider SqlServer

      - name: Seed
        if: ${{ github.event.inputs.action == 'Seed' || github.event.inputs.action == 'Migrate and Seed' }}
        working-directory: src/api/AMP.EMS.API
        run: dotnet run /seed
